# Stage 1
FROM node:10-alpine as build
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build --prod
 
# Stage 2
FROM nginx:alpine
COPY --from=build /app/dist/angular-app/ /usr/share/nginx/html

